name: 'Robot Framework Open'
description: 'Run Robot Framework tests'
inputs:
  allowed_shared_memory:
    description: 'Shared memory that Docker container is allowed to use'
    required: true
    default: '1g'
  browser:
    description: 'Browser to use'
    required: true
    default: 'chrome'
  robot_threads:
    description: 'Execute tests in parallel'
    required: true
    default: 1
  pabot_options:
    description: 'Extra settings for parallel execution. https://github.com/mkorpela/pabot#command-line-options'
    required: true
    default: ''
  robot_options:
    description: 'Extra options for robot command'
    required: true
    default: ''
  screen_color_depth:
    description: 'Color depth of the virtual screen'
    required: true
    default: 24
  screen_height:
    description: 'Height of the virtual screen'
    required: true
    default: 1080
  screen_width:
    description: 'Width of the virtual screen'
    required: true
    default: 1920
  robot_tests_dir:
    description: 'Directory where Robot tests are located in the repository'
    required: true
    default: 'robot_tests'
  robot_resources_dir:
    description: 'Directory where Robot resources are located in the repository'
    required: true
    default: 'resources'    
  robot_username_login:
    description: 'Enter the environment variable for your application's login user name'
    required: true
    default: 'fulano@mail.com.br'    
  robot_password_user:
    description: 'Enter the environment variable for your application login password'
    required: true
    default: '123456'        
  robot_reports_dir:
    description: 'Where will the report from test be saved'
    required: true
    default: 'reports'
  robot_runner_image:
    description: 'The docker image which will be used to execute the tests'
    required: true
    default: 'ppodgorsek/robot-framework:latest'


runs:
  using: 'composite'
  steps:
    - shell: bash
      run: ${{ github.action_path }}/test.sh
      env:
        ALLOWED_SHARED_MEMORY: ${{ inputs.allowed_shared_memory }}
        BROWSER: ${{ inputs.browser }}
        ROBOT_THREADS: ${{ inputs.robot_threads }}
        PABOT_OPTIONS: ${{ inputs.pabot_options }}
        ROBOT_OPTIONS: ${{ inputs.robot_options }}
        SCREEN_COLOR_DEPTH: ${{ inputs.screen_color_depth }}
        SCREEN_HEIGHT: ${{ inputs.screen_height }}
        SCREEN_WIDTH: ${{ inputs.screen_width }}
        ROBOT_TESTS_DIR: ${{ inputs.robot_tests_dir }}
        ROBOT_REPORTS_DIR: ${{ inputs.robot_reports_dir }}
        ROBOT_USERNAME_LOGIN: ${{ inputs.robot_username_login }}
        ROBOT_PASSWORD_USER: ${{ inputs.robot_password_user }}
        ROBOT_RESOURCES_DIR: ${{ inputs.robot_resources_dir }}
        ROBOT_RUNNER_IMAGE: ${{ inputs.robot_runner_image }}